version: "3.7"

services:
  router:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./router
    ports:
      - "9090:80"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - JWT_SECRET_KEY=ravjotyolo
    volumes:
      - ./api/:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    environment:
      - REACT_APP_SERVER_URL=/api
    volumes:
      - /app/node_modules
      - ./client:/app

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
