version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=strathyunit
      - MYSQL_USER=strathyunit
      - MYSQL_PASSWORD=strathyunit
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/strathyunit?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=strathyunit
      - SPRING_DATASOURCE_PASSWORD=strathyunit
      - JWT_SECRET_KEY=ravjotyolo
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8080/api
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - frontend

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
