# Setting base
FROM openjdk:8-jdk-alpine

# Setting the working directory
WORKDIR /app

# Installing maven
ENV MAVEN_VERSION 3.5.4
ENV MAVEN_HOME /usr/lib/mvn
ENV PATH $MAVEN_HOME/bin:$PATH

RUN wget http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  tar -zxvf apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  rm apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  mv apache-maven-$MAVEN_VERSION /usr/lib/mvn

# Copy pom file
COPY ./pom.xml ./

RUN mvn dependency:go-offline

# Copying the code
COPY ./ ./

# Running the code
CMD [ "mvn","clean","spring-boot:run" ]